pipeline:
    test:
        image: node:8.2.0
        commands:
            - npm install -q
            - npm run lint -q
    package:
        image: node:8.2.0
        commands:
            - npm run pack -q
        when:
            event: tag
    publish:
        image: plugins/npm
        folder: dist
        when:
            event: tag
    slack:
        image: plugins/slack
        channel: teknisk-dev
        username: drone
        when:
            event: [push, tag]
            status:  [ failure, success ]